# -*- coding: utf-8 -*-
"""cashier modul.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17wi3sP_b3K69QSj5LDy0iZOwwSvaR6wn
"""

class Transaction():
  #Dictionary data transaksi belanja customer
    def __init__(self):
      self.data_item = dict() #nama item sebagai index

    
    #menambahkan data item yang ingin dibeli
    def add_item(self, nama_item, jumlah_item, harga_item):
        self.data_item[nama_item.lower()] = [jumlah_item, harga_item]

    #mengganti nama item jika terjadi kesalahan penulisan
    def update_nama_item(self, nama_item, nama_item_baru):
        self.data_item[nama_item_baru.lower()] = self.data_item.pop(nama_item)
    
    #mengganti jumlah item yang akan dibeli
    def update_jumlah_item(self, nama_item, jumlah_baru):
      try:
        self.data_item[nama_item.lower()][0] = jumlah_baru
      except KeyError:
        print('Terdapat kesalahan input data, periksa nama_item')
    
    #mengganti harga item yang akan dibeli jika terjadi kesalahan penulisan
    def update_harga_baru(self, nama_item, harga_baru):
      try:
        self.data_item[nama_item.lower()][1] = harga_baru
      except KeyError:
        print('Terdapat kesalahan input data, periksa nama_item')

    #menghapus item yang tidak ingin dibeli
    def delete_item(self, nama_item):
        self.data_item.pop(nama_item.lower())
    
    #menghapus seluruh item sekaligus
    def reset_transaction(self):
        self.data_item.clear
        print('Semua item berhasil dihapus')

    #mengecek data pesanan yang dimasukkan    
    def check_order(self):
        try:
          print('Pesanan sudah benar')
          print(self.data_item)
        except KeyError:
          print('Terdapat kesalahan input data')
    
    #menampilkan seluruh data yang dipesan beserta total harga
    def total_price(self):
        print('Berikut seluruh pesanan anda')
        print(self.data_item)
        total_harga = 0
        for i in list(self.data_item.keys()):
          total_harga += self.data_item[i][0]*self.data_item[i][1]

      #menghitung total harga jika mendapatkan diskon
        if total_harga > 200_000:
          total_harga *= 0.95
          print('Selamat anda mendapatkan diskon sebesar 5%')
        elif total_harga > 300_000:
          total_harga *= 0.92
          print('Selamat anda mendapatkan diskon sebesar 8%')
        elif total_harga > 500_000:
          total_harga *= 0.90
          print('Selamat anda mendapatkan diskon sebesar 10%')
        else:
          pass
        print(f'Total belanja yang harus dibayarkan adalah:',total_harga)