# -*- coding: utf-8 -*-
"""cashier main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10HKw3pjc1W7-cTG4LDvpnzTfXGsccADU
"""

from cashier_modul import Transaction

trsc1 = Transaction()

#test 1
trsc1.add_item('Ayam Goreng', 2, 20_000)
trsc1.add_item('Pasta Gigi', 3, 12_000)
trsc1.check_order()

#test 2
trsc1.delete_item('Pasta Gigi')
trsc1.check_order()

#test 3
trsc1.reset_transaction()

#test 4
trsc1.add_item('Ayam Goreng', 2, 20_000)
trsc1.add_item('Pasta Gigi', 3, 15_000)
trsc1.add_item('Mainan Mobil', 1, 200_000)
trsc1.add_item('Mie instan', 5, 3_000)
trsc1.total_price()